### ISSUE TITLE
markdown无序列表语法渲染不符合预期

### ISSUE THREAD

**Issue by XiaoQin0000** [chaooo/hexo-theme-BlueLake#10]
### markdown语法
```
 - 反射调用构造方法初始化新的变量
```

### 渲染H5
```
<ul>
<li><p>反射调用构造方法初始化新的变量</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">newInstance</span><span class="params">()</span> <span class="keyword">throws</span> IllegalAccessException, InstantiationException </span>&#123;</div><div class="line">        FileIO fileIO = FileIO.class.newInstance();</div><div class="line"> &#125;</div></pre></td></tr></table></figure>
<p>​</p>
</li>
```
### 显示结果
![markdown](https://cloud.githubusercontent.com/assets/18345570/22911380/655ad7c0-f29a-11e6-9395-74dd17ff2bfa.png)

### 参考网站

[https://xiaoqinyu0000.github.io/Java/JavaSingleton/](https://xiaoqinyu0000.github.io/Java/JavaSingleton/)

**Comment by chaooo** [comment]
你用的什么浏览器什么版本？我刚测试我这边显示正常，你的参考网址点进去打不开

**Comment by XiaoQin0000** [comment]
## 我用的是Chrome（56.0.2924.87 (64-bit)），参考网站是：https://xiaoqinyu0000.github.io/Java/JavaSingleton/   
## 麻烦你再试试

**Comment by chaooo** [comment]
我又更新了下，替换最新的style.styl试试，位置在`BlueLake\source\css\style.styl`。

**Comment by XiaoQin0000** [comment]
好的，谢谢。今晚试一下。@closed

**Comment by XiaoQin0000** [comment]
昨晚更新了主题，重新渲染后解决了问题。感谢作者。@chaooo
