### ISSUE TITLE
求作者QQ或微信，我想为BlueLake贡献一些小功能

### ISSUE THREAD

**Issue by 841809077** [chaooo/hexo-theme-BlueLake#101]
目前我的博客已经添加了文末打赏、图片放大、自定义图标、右侧二维码展示等，我的博客地址：https://841809077.github.io/  ，想将这些功能贡献出来，需要联系作者，希望作者可以看到此贴。

求个好友位，认识一下，谢谢

**Comment by chaooo** [comment]
你好，很抱歉这么晚才看到你的留言，我的微信号：zhengchaooo
可以加个好友互相学习，如果对BlueLake有好的想法，或扩展功能 可以直接提交pull request，我看到后测试通过也会合并上去。

**Comment by 841809077** [comment]
好的
