### ISSUE TITLE
version: 2.0.4， 置顶失效。

### ISSUE THREAD

**Issue by mingfuyan** [chaooo/hexo-theme-BlueLake#104]
详见 [https://solodance.top/](https://solodance.top/)

![](http://imglf4.nosdn0.126.net/img/T0t4Z3Z5a254aFR0SzZ5QWRqZUpvRk5tYXNYSmtwblRMRjFWUHN2ZDl6ajEyTk1RZWZIUHZnPT0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0)

**Comment by chaooo** [comment]
置顶需要插件的支持，请问安装插件了么？

**Comment by chaooo** [comment]
`npm install hexo-generator-index-pin-top --save`

**Comment by mingfuyan** [comment]
已解决， 感谢

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
