### ISSUE TITLE
关于分类显示

### ISSUE THREAD

**Issue by zcl1021** [chaooo/hexo-theme-BlueLake#107]
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

配置文件里那个分类没有注释掉，但是页面还是没有，请问在哪个文件设置

**Comment by zcl1021** [comment]
已经解决了

**Comment by WilliamAdolph** [comment]
> 已经解决了

你好，请问下你有遇到过那个首页那里点击归档什么的，就archive页面报错的吗？
![image](https://user-images.githubusercontent.com/36332969/90103640-6e51fb00-dd75-11ea-9124-ea8cf8309dae.png)
就我yidian一点这里的时候，就一直在转，控制台的话我看到了是这个archive.jade的报错，
![image](https://user-images.githubusercontent.com/36332969/90103724-92add780-dd75-11ea-8d2f-6724241825b5.png)
但是不知道怎么改，想问下你有遇到过吗

**Comment by Anthony-fei** [comment]
> > 已经解决了
> 
> 你好，请问下你有遇到过那个首页那里点击归档什么的，就archive页面报错的吗？
> ![image](https://user-images.githubusercontent.com/36332969/90103640-6e51fb00-dd75-11ea-9124-ea8cf8309dae.png)
> 就我yidian一点这里的时候，就一直在转，控制台的话我看到了是这个archive.jade的报错，
> ![image](https://user-images.githubusercontent.com/36332969/90103724-92add780-dd75-11ea-8d2f-6724241825b5.png)
> 但是不知道怎么改，想问下你有遇到过吗

我也遇到了这个问题，请问是怎么解决的呢
