### ISSUE TITLE
多级无序列表缩进问题

### ISSUE THREAD

**Issue by XiaoQin0000** [chaooo/hexo-theme-BlueLake#11]
- markdown：

```
- 代表产品：
  - [科技美学](http://www.dingdone.com/case/2016-01-13/970191.html)
  - [都市云阳](http://www.dingdone.com/case/2016-02-15/1045425.html)
  - [么上兼职](http://www.dingdone.com/case/2015-11-30/838092.html)
```

 - 期待效果：
![image](https://cloud.githubusercontent.com/assets/18345570/23388791/4be50936-fd9f-11e6-9b58-4eae52fbc621.png)

 - 实际显示效果：
![image](https://cloud.githubusercontent.com/assets/18345570/23388755/0dd6970e-fd9f-11e6-87fa-11a527caa0fd.png)

 - H5：
```
<li><p>代表产品：</p>

<ul>

<li>科技美学</li>

<li>都市云阳</li>

<li>么上兼职</li>

</ul>

</li>

```

 - 使用浏览器：

chrome  56.0.2924.87 (64-bit)

**Comment by chaooo** [comment]
已更新，替换`source\css\style.styl`或修改其459行
``` stylus
    ul,ol
      margin: 1em
```
修改为：
``` stylus
    ul,ol
      margin: 0
      padding: 0 0 0 2em
      list-style-position: inside
```

**Comment by XiaoQin0000** [comment]
@chaooo 感谢您的重视，但我重新pull主题之后产生了新的问题。

 - markdown：
```
- 代表产品：
  - [科技美学](http://www.dingdone.com/case/2016-01-13/970191.html)
  - [都市云阳](http://www.dingdone.com/case/2016-02-15/1045425.html)
  - [么上兼职](http://www.dingdone.com/case/2015-11-30/838092.html)
```

 - 期待效果：
![](https://cloud.githubusercontent.com/assets/18345570/23388791/4be50936-fd9f-11e6-9b58-4eae52fbc621.png)

 - 实际显示效果：
![image](https://cloud.githubusercontent.com/assets/18345570/23443414/a20f3c08-fe69-11e6-86aa-e282f075677a.png)

 - H5：
```
<li><p>代表产品：</p>
<ul>
<li><a href="http://www.dingdone.com/case/2016-01-13/970191.html" target="_blank" rel="external">科技美学</a></li>
<li><a href="http://www.dingdone.com/case/2016-02-15/1045425.html" target="_blank" rel="external">都市云阳</a></li>
<li><a href="http://www.dingdone.com/case/2015-11-30/838092.html" target="_blank" rel="external">么上兼职</a></li>
</ul>
</li>
```

**Comment by chaooo** [comment]
怎么会换行，重新替换source\css\style.styl试试。

**Comment by chaooo** [comment]
我的也是chrome 56.0.2924.87 (64-bit)/win10，但显示是正常的

**Comment by XiaoQin0000** [comment]
重新pull之后解决了问题。谢谢！
