### ISSUE TITLE
使用主题 报错问题

### ISSUE THREAD

**Issue by xiaohao845965** [chaooo/hexo-theme-BlueLake#113]
归档 标签 循环  时 函数 groupBy 与 post.date.format 函数 也报未定义错误

**Comment by AriaLyy** [comment]
+1，升级了hexo 5.1 就出现了这个问题

**Comment by stevenjoezhang** [comment]
Hexo 移除了 lodash，因此无法使用 `_.groupBy`

**Comment by Anthony-fei** [comment]
> 归档 标签 循环 时 函数 groupBy 与 post.date.format 函数 也报未定义错误

请问这个问题怎么解决呀？

**Comment by chaooo** [comment]
是的，Hexo 5.0.0+ 去除了全局变量中的 Lodash影响的，暂时可以先降低博客中Hexo的版本来使用主题。近期我抽时间会更新主题来兼容最新版本。
