### ISSUE TITLE
前端gittalk报错

### ISSUE THREAD

**Issue by Tanky-Zhang** [chaooo/hexo-theme-BlueLake#118]
你好，首先非常感谢您能够提供这么好的主题，我在使用这个主题的过程中发现了一个gittalk的问题，那就是在页面一开始的时候会有前端报错产生，如下：
![image](https://user-images.githubusercontent.com/48041180/114289939-4bb3e580-9aae-11eb-955a-9ff288b04f62.png)
这是在您的博客首页截取的，我想这应该不是我操作的问题，所以想就这个问题咨询一下。非常感谢！

**Comment by Tanky-Zhang** [comment]
另外想咨询一个和归档有关的问题:
![image](https://user-images.githubusercontent.com/48041180/114290670-d5b27d00-9ab3-11eb-8ebc-ef6eff44d4ff.png)
我做了如上图的配置，但是好像归档页面的时候还是默认给按照年进行展示，如下：
![image](https://user-images.githubusercontent.com/48041180/114290691-01356780-9ab4-11eb-9955-959f93f75fd2.png)
请问是我的配置有问题吗，非常感谢！

**Comment by chaooo** [comment]
第一个问题是gitalk国内访问不太稳定，第二个问题配置是侧边栏的归档，归档页面暂不支持配置
