### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by gaochunchun** [chaooo/hexo-theme-BlueLake#12]
在根目录下修改_config.yml文件# Site 下的subtitle：中文文字
language: zh-CN  部署到git后访问为乱码。
链接：http://gao_chun.oschina.io/

**Comment by chaooo** [comment]
一般配置的时候 `:` 后面要空一格，（英文半角的空格）

**Comment by gaochunchun** [comment]
您好，感谢回复。
按照你说的方法特意留意重新写了一下，还是乱码 ， 把.deploy_git目录删除重新发布也不行，还有其他可能导致乱码的原因吗

**Comment by chaooo** [comment]
你把HEXO重新全局安装下，然后在项目根目录再运行一下npm install，再重新发布试试

**Comment by gaochunchun** [comment]
试了一下，还是不可以，不过出现如下警告信息，我的是windows 64系统：
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

和版本有关系吗，hexo 3.2.2   ----  Git  version 1.9.5.msysgit.1   ----   node.js  v6.9.5

**Comment by gaochunchun** [comment]
修改完成后，在 hexo clean --- hexo generate  之后，主目录下的public目录中index.html里，就已经乱码了 ，应该是在generate 时导致的，我尝试把.deploy_git目录下的index.html中乱码修改为标题，不执行hexo g直接hexo d 就没乱码了，但只要执行了hexo g后，网页上的副标题中文就会成乱码

**Comment by chaooo** [comment]
也可能是你的编辑器没设置好，设置编辑器的字符集为UTF-8

**Comment by chaooo** [comment]
其他主题也一样还是只有这个主题乱码？

**Comment by gaochunchun** [comment]
。。。我的错，既然没注意编辑器是ANSI编码格式 。 谢谢博主。

**Comment by chaooo** [comment]
嗯，没事，解决了就好
