### ISSUE TITLE
卜算子开启后，图标显示，数字未显示

### ISSUE THREAD

**Issue by LiJunYi2** [chaooo/hexo-theme-BlueLake#121]
![1](https://user-images.githubusercontent.com/40384503/127826864-8967d14d-7ad7-4a75-a212-83958fab7cf9.png)
![2](https://user-images.githubusercontent.com/40384503/127826886-9ee76ca4-45dc-488a-aa51-7504a7219931.png)

**Comment by chaooo** [comment]
卜算子服务器压力越来越大，感觉经常在报错
