### ISSUE TITLE
代码块背景

### ISSUE THREAD

**Issue by unixfbi** [chaooo/hexo-theme-BlueLake#16]
您好，这个主题代码块背景颜色是白色的，能不能让用户自己设置这个代码块的颜色啊？我想让代码块的背景颜色是黑色。谢谢

by  UnixFBI  

 unixfbi.com

**Comment by chaooo** [comment]
可在网上下载喜欢的highlight替换 themes\BlueLake\source\css\highlight.styl，或者直接在此基础上更改，主题下次更新时会考虑深色系列可供选择。
