### ISSUE TITLE
网易云跟贴集成不成功

### ISSUE THREAD

**Issue by idersan** [chaooo/hexo-theme-BlueLake#17]
网易云跟贴集成不成功

**Comment by chaooo** [comment]
能说一下具体表现吗？我这边测试是可以的。

**Comment by idersan** [comment]
在 themes\BlueLake\_config.yml  中添加了网易云跟贴的 productKey 如下
`cloudTie: c4cd25e250584e1fxxxxxxxxx ## 网易云跟帖(productKey)`
其它任何地方没修改。运行起来的时候不显示。

**Comment by idersan** [comment]
我看到 themes\BlueLake\layout\_partial\comments.jade 中网易云跟帖注释了，这个有影响吗？@chaooo
```
if theme.comment.cloudTie
   #cloud-tie-wrapper.cloud-tie-wrapper
```

**Comment by chaooo** [comment]
必须要在线上才可以哦，云跟帖本地不行的，` #cloud-tie-wrapper.cloud-tie-wrapper`是jade语法并不是注释，他相当于HTML的<div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>，评论就加载在这个标签内。
