### ISSUE TITLE
some error occur when i change theme to BlueLake

### ISSUE THREAD

**Issue by icanfly** [chaooo/hexo-theme-BlueLake#2]
the error stack trace like this:

            <a id="main-nav-toggle" class="nav-icon"></a>
             <% for (var i in theme.menu){ %>
               <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
             <% } %>
          </nav>
        <nav id="sub-nav">

path.substring is not a function 

my env :

hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 16.1.0 darwin x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j

**Comment by chaooo** [comment]
This is the grammar of EJS,  but I was using JADE to write the layout.

**Comment by chaooo** [comment]
You can run `hexo clean` before `hexo generate`,when you change theme.
