### ISSUE TITLE
标签命名问题

### ISSUE THREAD

**Issue by findneo** [chaooo/hexo-theme-BlueLake#24]
无意中发现，当标签为`null`或`NULL`时，主题无法处理和显示，为`NuLl`及类似词时没有问题。虽然无伤大雅，但还是提一下:p

**Comment by findneo** [comment]
想当然了，除了`null`和`NULL`，`Null`也无法处理；经尝试`NuLl`和`NUll`没有问题，其他未实验。

**Comment by sunmingshuai** [comment]
更新后的about页面显示不出来 应该是解析的bug

**Comment by Jesse121** [comment]
也遇到about页面解析不出来

**Comment by chaooo** [comment]
已修复about页面，请更新page.jade和_config.yml

**Comment by chaooo** [comment]
应该没有人会把标签设为null吧，要研究这个问题应该要去看hexo源码了。
