### ISSUE TITLE
文章多级分类问题

### ISSUE THREAD

**Issue by sunmingshuai** [chaooo/hexo-theme-BlueLake#26]
大神能不能加个文章多级别分类功能啊 现在只能一级分类 有些情况下不太好用了 感谢

**Comment by chaooo** [comment]
你好，文章分类不是主题能决定的，是hexo引擎决定的，你看看hexo的文档看有没有多级分类。

**Comment by JinghuiXiao** [comment]
本地运行，页面出现  两个插件都装过了。试过重装 还是不行
extends base - var current_title = page.title || tag.name || category.name || site.title block title if config.subtitle title= config.title + ' | ' + config.subtitle else title= config.title block content for post in page.posts.toArray() .post h1.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo a.ds-thread-count(data-thread-key=post.path, href=url_for(post.path) + '#comments') if theme.disqus a.disqus-comment-count(data-disqus-identifier=post.path, href=url_for(post.path) + '#disqus_thread') if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = 0 - for (var i = 0; i < 5; ++i) { - br = post.content.indexOf('\n',br+1) if br<0 - break if br >150 - break - } if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class='readmore') a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr', src='//#{theme.disqus}.disqus.com/count.js', async)

**Comment by chaooo** [comment]
npm install hexo-renderer-jade --save
npm install hexo-renderer-stylus --save
这两个渲染器有装吗？

**Comment by JinghuiXiao** [comment]
都装了。还试了无数遍




发自网易邮箱大师
在2017年05月10日 20:06，郑超 写道：

npm install hexo-renderer-jade --save
npm install hexo-renderer-stylus --save
这两个渲染器有装吗？

**Comment by chaooo** [comment]
不应该啊，其他主题是正常的吗？

**Comment by JinghuiXiao** [comment]
有的正常，有的不正常，我重新试了好多主题




发自网易邮箱大师
在2017年05月10日 20:10，郑超 写道：

不应该啊，其他主题是正常的吗？

**Comment by JinghuiXiao** [comment]
这是我最纳闷的地方。我也用试过淘宝景象装，插件都装成功了。结果显示的还是这




发自网易邮箱大师
在2017年05月10日 20:11，JinghuiXiao 写道：
有的正常，有的不正常，我重新试了好多主题




发自网易邮箱大师
在2017年05月10日 20:10，郑超 写道：

不应该啊，其他主题是正常的吗？

**Comment by chaooo** [comment]
那你本地环境应该是有问题的，试试重装nodeJS和hexo-cli

**Comment by chaooo** [comment]
hexo-cli全局安装
npm install -g hexo-cli

**Comment by JinghuiXiao** [comment]
这都试过了。明天再试试node重装。如果环境没问题，应该是可以运行的吧？




发自网易邮箱大师
在2017年05月10日 20:15，郑超 写道：

hexo-cli全局安装
npm install -g hexo-cli

**Comment by strivebo** [comment]
我也是那个问题

**Comment by chaooo** [comment]
jade模板渲染器（hexo-renderer-jade）更新导致的，删除本地node_modules\hexo-renderer-jade目录，
安装hexo-renderer-jade 0.3.0版本就可以了。
npm install hexo-renderer-jade@0.3.0 --save

**Comment by VN666** [comment]
多级分类这个问题有解决吗
