### ISSUE TITLE
本地运行也是错误，别的主题没有问题。

### ISSUE THREAD

**Issue by robotneo** [chaooo/hexo-theme-BlueLake#29]
本地运行，页面出现 两个插件都装过了。试过重装 还是不行
extends base - var current_title = page.title || tag.name || category.name || site.title block title if config.subtitle title= config.title + ' | ' + config.subtitle else title= config.title block content for post in page.posts.toArray() .post h1.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo a.ds-thread-count(data-thread-key=post.path, href=url_for(post.path) + '#comments') if theme.disqus a.disqus-comment-count(data-disqus-identifier=post.path, href=url_for(post.path) + '#disqus_thread') if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = 0 - for (var i = 0; i < 5; ++i) { - br = post.content.indexOf('\n',br+1) if br<0 - break if br >150 - break - } if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class='readmore') a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr', src='//#{theme.disqus}.disqus.com/count.js', async)

**Comment by whonchen** [comment]
我也有类似的问题

**Comment by yangbin194** [comment]
我的也是,试过很多次都是网页生成这些代码. 但是我发现还是能够成功生成atom.xml(也就是rss订阅)的.
也不知道什么原因, node 和 hexo 都重新装过了.那两个渲染用的工具也安装了.

**Comment by chaooo** [comment]
没有安装渲染器
npm install hexo-renderer-jade --save
npm install hexo-renderer-stylus --save

**Comment by hong-ll** [comment]
渲染器安装了，也是出现这种情况

**Comment by chaooo** [comment]
嗯嗯，我再看看，再测试下

**Comment by jaybodev** [comment]
我也是出现同样问题 @chaooo

**Comment by chaooo** [comment]
jade模板渲染器（hexo-renderer-jade）更新导致的，删除本地node_modules\hexo-renderer-jade目录，
安装hexo-renderer-jade 0.3.0版本就可以了。
npm install hexo-renderer-jade@0.3.0 --save

**Comment by strivebo** [comment]
好了，
