### ISSUE TITLE
WARN  No layout: index.html

### ISSUE THREAD

**Issue by philipbo** [chaooo/hexo-theme-BlueLake#30]
作者， 你好，挺喜欢这个主题的。
但是按照文档操作运行后，出错：WARN  No layout: index.html
请问怎么解决?

**Comment by fupinglee** [comment]
@philipbo 我估计是你主题的名字和文件夹对应不上。
`git clone https://github.com/chaooo/hexo-theme-BlueLake.git themes/BlueLake`
根_config.yml
`theme: BlueLake`

**Comment by summerlly** [comment]
我将 BlueLake 全都换成小写之后就应用成功了,不知道是不是大小写的原因.
