### ISSUE TITLE
分享按钮在localhost环境能显示在.github.io就不行了

### ISSUE THREAD

**Issue by zhangyongbo** [chaooo/hexo-theme-BlueLake#34]
分享按钮在localhost环境能显示在.github.io就不行了
http://ogeomshjx.bkt.clouddn.com//Fh6r3SvtiK07xwt8-x1p2yxSeNLO
![](http://ogeomshjx.bkt.clouddn.com//Fh6r3SvtiK07xwt8-x1p2yxSeNLO)

**Comment by chaooo** [comment]
我这边测试是正常的，我猜测可能是由于网络原因百度分享的样式没有加载进来，我是把分享的JS代码放到页面尾部的，你可以尝试把它的JS代码放头部试试。
