### ISSUE TITLE
添加文章，界面出现post嵌套

### ISSUE THREAD

**Issue by arvin0** [chaooo/hexo-theme-BlueLake#35]
BUG现象：
![1](https://user-images.githubusercontent.com/5111701/29055463-479670d6-7c2f-11e7-9ef6-57c3f7744e36.jpg)

**Comment by arvin0** [comment]
文章里 有  这个，页面上就会出现文章之间相互嵌套的BUG，

**Comment by arvin0** [comment]
是因为从博客园导出的文章，里面有html标签；more在标签里，就不能辨别，会出现文章嵌套BUG；不过我看有的hexo主题可以分辨

**Comment by chaooo** [comment]
上面图片没显示出来，我现在还不清楚具体怎样的嵌套。

**Comment by chaooo** [comment]
不过我刚去你博客看了是正常的啊，已经解决了？

**Comment by arvin0** [comment]
嗯，算是迂回解决吧，我把more从md文章里的div或者code 标签里提出来，放到外面，就可以正常显示了。不过要是more功能的兼容性好点就好了，

下面是more出BUG时，在md文章中的情形：
![12](https://user-images.githubusercontent.com/5111701/29055685-7152dad0-7c30-11e7-90a7-1b7711f9f13f.jpg)
![13](https://user-images.githubusercontent.com/5111701/29055692-7616d4c2-7c30-11e7-9565-171a1b37d86a.jpg)

**Comment by chaooo** [comment]
直接再 .md文件里写`<div>`是有问题的吧。

**Comment by arvin0** [comment]
理论上应该不推荐的，不过实际上也是可以的，具体效果 http://localhost:4000/2017/02/24/6522011/

**Comment by chaooo** [comment]
解决了就好，你这本地链接我是没法看的。

**Comment by arvin0** [comment]
嗯嗯，我刚才也发现了发的本地链接，现在改了；其实是原来在博客园里的文章，然后导出的，有标签，懒得改；
