### ISSUE TITLE
About页面的图片显示不正常

### ISSUE THREAD

**Issue by KangShanR** [chaooo/hexo-theme-BlueLake#37]
自己生成了Aboubt页面，但其中的photo链接过去后显示水平方向上被压缩了。我的图片是2100*627，jpg格的

**Comment by chaooo** [comment]
你可以自己根据图片修改下样式

**Comment by chaooo** [comment]
路径：hexo-theme-BlueLake/source/css/style.styl：812行开始about页面

**Comment by KangShanR** [comment]
谢谢提醒。
