### ISSUE TITLE
请教一下大神，如果想自定义页面背景的问题

### ISSUE THREAD

**Issue by KangShanR** [chaooo/hexo-theme-BlueLake#38]
如果想自定义整个页面的背景色（想换一个暖和一点的颜色），可以定制吗？如果可以改哪个配置文件夹的哪个参数？

**Comment by chaooo** [comment]
hexo-theme-BlueLake/source/css/style.styl：115行

**Comment by KangShanR** [comment]
谢谢，改到了。
