### ISSUE TITLE
安装RSS和siteMap的错误：

### ISSUE THREAD

**Issue by KangShanR** [chaooo/hexo-theme-BlueLake#39]
站主你好，
我按照你的说明安装了feed,sitemap,baidu-sitemap插件后，也在public目录下生成了atom.xml，在网页上rss链接也是指向这个atom.xml的，点击过去后就是浏览器找开了这个atom.xml文件的效果。
请问这是安装插件或者其它哪儿的问题吗？

**Comment by chaooo** [comment]
应该是浏览器的问题，有的浏览器好像并不解析XML，用火狐试试。
