### ISSUE TITLE
主页右侧工具栏跑到下面

### ISSUE THREAD

**Issue by dinghmcn** [chaooo/hexo-theme-BlueLake#42]
主页右侧工具栏跑到下面，其他页面是正常的，
生成的页面结构出错
![screenshot_20170917_215805](https://user-images.githubusercontent.com/15715884/30521511-5069cbac-9bf3-11e7-93b6-d3fd915bfd33.png)

**Comment by chaooo** [comment]
要仔细检查代码哦
