### ISSUE TITLE
页面打开速度过慢

### ISSUE THREAD

**Issue by antime** [chaooo/hexo-theme-BlueLake#43]
打开网页的速度过慢，其实网页是加载出来了，就是不显示出来，等叉掉转圈的状态页面就立马显示出来了

**Comment by kengdingxiaoman** [comment]
可以看下是不是因为 fonts.css.network 换了域名，所以请求超时，基本都要30秒后才能打开网页。
/layout/base.jade 第 28行
link(rel="stylesheet", type="text/css", href="//fonts.css.network/css?family=Source+Code+Pro")

其中用到的地址: fonts.css.network 更换了域名，访问不了了

解决方案：把 fonts.css.network 换成 fonts.neworld.org

28行改为：
link(rel="stylesheet", type="text/css", href="//fonts.neworld.org/css?family=Source+Code+Pro")

**Comment by antime** [comment]
非常感谢，顺利解决

**Comment by zDream** [comment]
@kengdingxiaoman @antime 解决后怎么tag下的标签字体格式都变了

**Comment by p1r06u3** [comment]
2018年06月19日11:28:32
fonts.neworld.org也不能用了
换这个吧：
fonts.loli.net
