### ISSUE TITLE
服务启动后无法访问，报异常

### ISSUE THREAD

**Issue by JPMonty** [chaooo/hexo-theme-BlueLake#49]
**如下图所示：**
![1 default node 2018-02-24 17-40-39](https://user-images.githubusercontent.com/18655885/36628925-250ffce6-198a-11e8-9f7b-87361d9d3589.png)

未修改过主题文件代码

**Comment by chaooo** [comment]
没安装jade模板渲染器吧，主题并非用ejs写的哦，
