### ISSUE TITLE
以4个空格或者tab键缩进的内容不被识别为代码

### ISSUE THREAD

**Issue by dieangel** [chaooo/hexo-theme-BlueLake#5]
这个何解。

同时单行代码过长的话不会出现滚动条。而是直接撑到其他地方去了

看起来有点丑陋。

**Comment by chaooo** [comment]
单行代码过长不出现滚动条问题已解决，请替换新的主题样式文件就好
hexo 3.1.1开始，不支持代码自动检测，需要把自动检测属性设为true，这也许是tab不被识别的原因吧，
或者包裹代码块有没有问题。
{% codeblock [title] [lang:language] [url] [link text] %}
      代码块~
{% endcodeblock %}
或者：
``` [language] [title] [url] [link text]
      代码块~
```

**Comment by dieangel** [comment]
还是希望能进行四个空格这样的代码识别
