### ISSUE TITLE
反馈个bug：序号下一段的文字不会换行

### ISSUE THREAD

**Issue by cloudpanl** [chaooo/hexo-theme-BlueLake#55]
网页上显示是这样的，例如：

经典的软件设计原则：

1、保持简单，愚蠢（KISS）
2、不要重复自己（DRY）
然后是Red Hat的云原生容器设计原则：

楼主可能把代码写反了，序号的文字应该跟上一段靠拢，而不是跟下一段靠拢。

**Comment by chaooo** [comment]
因为每个段落p标签有个margin，现在把ul,ol也加上margin了
