### ISSUE TITLE
页面的字体怎么换？微博替换不了自己的

### ISSUE THREAD

**Issue by wtgg** [chaooo/hexo-theme-BlueLake#56]
安装之后，想换一种英文字体怎么换
![qq 20180331162755](https://user-images.githubusercontent.com/20369905/38161390-8f759352-3500-11e8-8f66-0db795a1ef44.png)

？标题加粗怎么设置？

**Comment by chaooo** [comment]
换字体的话修改样式文件，加粗参考Markdown语法`**这是加粗的文字** `
