### ISSUE TITLE
请问如何添加mathjax模块？

### ISSUE THREAD

**Issue by Jingyi97** [chaooo/hexo-theme-BlueLake#60]
Dear Chao,
谢谢您制作并分享这个主题。我的博客使用了BlueLake主题，我近期想写一些关于数学的文章，需要用到LaTeX代码。我尝试了别人提供的技术教程（见https://ranmaosong.github.io/2017/11/29/hexo-support-mathjax/ ），但是编译之后，LaTeX代码无法被渲染。想请问一下，这个问题该如何解决？如果BlueLake主题在设计之初没有加入对Mathjax的支持，可否请您更新一个模块？非常感谢。
Best wishes,
Jingyi

**Comment by chaooo** [comment]
谢谢反馈，有时间的时候我会加入对Mathjax的支持，最近有点忙，这个主题没时间去维护，有时间的时候我会再去优化和添加新功能支持。
 
发件人: Jingyi97
发送时间: 2018年5月30日 22:28
收件人: chaooo/hexo-theme-BlueLake
抄送: Subscribed
主题: [chaooo/hexo-theme-BlueLake] 请问如何添加mathjax模块？ (#60)

Dear Chao,
谢谢您制作并分享这个主题。我的博客使用了BlueLake主题，我近期想写一些关于数学的文章，需要用到LaTeX代码。我尝试了别人提供的技术教程（见https://ranmaosong.github.io/2017/11/29/hexo-support-mathjax/），但是hexo g && hexo s之后，LaTeX代码无法被渲染。想请问一下，这个问题该如何解决？如果BlueLake主题在设计之初没有加入对Mathjax的支持，可否请您更新一个模块？非常感谢。
Best wishes,
Jingyi

**Comment by chaooo** [comment]
# MathJax Support
mathjax:
  enable: true  #true/false.
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
