### ISSUE TITLE
主题无法使用

### ISSUE THREAD

**Issue by xiaomizhou66** [chaooo/hexo-theme-BlueLake#66]
extends base - var current_title = page.title || tag.name || category.name || site.title block title if config.subtitle title= config.title + ' | ' + config.subtitle else title= config.title block content for post in page.posts.toArray() .post h2.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta if theme.comment.changyan.appid && theme.comment.changyan.appkey a.comment-count(href=url_for(post.path) + '#comments') span.cy_cmt_count(id = 'url::' + config.url +'/'+ post.path) = ''+ __('guestbook') + ',' span.cy_cmt_participate(id = 'url::' + config.url +'/'+ post.path) = ''+ __('participate') p span.date= post.date.format(config.date_format) if post.categories.length > 0 span for category in post.categories.toArray() a.category(href=url_for(category.path))= category.name if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = post.content.indexOf('\n') if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class='readmore') a(href=url_for(post.path))= __('Readmore') include _partial/paginator block pageOnly script(type='text/javascript', src=url_for(theme.js) + '/totop.js' + '?v=' + theme.version, async) if theme.comment.changyan.appid && theme.comment.changyan.appkey script(id="cy_cmt_num", src='http://changyan.sohu.com/upload/plugins/plugins.list.count.js' + '?clientId=' + theme.comment.changyan.appid)

**Comment by dmxiaoshen** [comment]
这个问题是怎么回事呀，我也碰到了，解决了吗？

**Comment by conn4575** [comment]
同遇到，下载了 hexo 官方的 demo，只改了一个主题就报错了，help！！
