### ISSUE TITLE
关于Bluelake主题添加版权信息的功能

### ISSUE THREAD

**Issue by 841809077** [chaooo/hexo-theme-BlueLake#68]
![f1h a ed s7 13yymz 8](https://user-images.githubusercontent.com/31361620/46620192-a2937980-cb56-11e8-8a9a-91da6c23d8a5.png)

**Comment by 841809077** [comment]
例如上图这样子的。

我对jade不太了解，请问有人实现过吗？

**Comment by chaooo** [comment]
已添加，更新最新主题
