### ISSUE TITLE
关于访问统计

### ISSUE THREAD

**Issue by cherubimLV** [chaooo/hexo-theme-BlueLake#69]
在主页中，访问统计没有值
在文章中没用文章阅读统计
以上是我刚使用的时候发现的，感谢大佬提供的主题，很喜欢这种风格

**Comment by David1840** [comment]
可以到BlueLake/layout/_partial下修改after_footer.jade，把文件开头的'dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js' 修改为 "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"就可以了

**Comment by David1840** [comment]
原因可看 http://busuanzi.ibruce.info/

**Comment by cherubimLV** [comment]
谢谢，已经改好了，成功显示了
