### ISSUE TITLE
侧边栏样式设置不成功

### ISSUE THREAD

**Issue by xiaomizhou66** [chaooo/hexo-theme-BlueLake#73]
设置了样式之后，（是在 style.stl 文件修改的）
然后在 http://localhost:4000 也预览成功，
但是在 https 网站上不能显示预想的样式。
请问这个侧边栏的样式是怎么需要怎么修改的？

**Comment by xiaomizhou66** [comment]
![image](http://liuxmoo.foryung.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20190119222229.png)
上面是本地浏览器预览
![image](http://liuxmoo.foryung.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20190119222313.png)
这是是线上网站

**Comment by xiaomizhou66** [comment]
请问可以帮忙看下这个是怎么解决么，谢谢，谢谢

**Comment by chaooo** [comment]
本地预览样式效果应该和线上一致，如不一致就是发布线上时没有重新生成项目。
