### ISSUE TITLE
ERROR Process failed: languages/tr.yml

### ISSUE THREAD

**Issue by KDWangBoss** [chaooo/hexo-theme-BlueLake#74]
1、YAMLException: duplicated mapping key at line 28, column 1:
    baidusitemap: Site Haritası
2、Warning: missing space before text for line 16 of jade file "E:\project\hexo\blog\themes\bluelake\layout\_partial\footer.jade"

**Comment by chaooo** [comment]
Thank you, already fixed, please get the latest code.
