### ISSUE TITLE
移动端页面适配出现问题

### ISSUE THREAD

**Issue by AriaLyy** [chaooo/hexo-theme-BlueLake#76]
版权信息的url过长的话，没有自动折叠，会导致宽度超出屏幕宽度，如下图所示：
地址：https://www.laoyuyu.me/2019/02/18/docker/dockerfile/
![image](https://user-images.githubusercontent.com/10437293/53789042-6b3ac480-3f5e-11e9-9c7d-3202993c0961.png)

**Comment by chaooo** [comment]
已修复，添加样式 .post-copyright blockquote a {word-break: break-all;}就好
