### ISSUE TITLE
Hexo相关文章的功能代码实现问题

### ISSUE THREAD

**Issue by chdlong** [chaooo/hexo-theme-BlueLake#77]
很喜欢这个主题，但是对jade从没接触过，折腾几天终于可以用了。
想给主题添加一个推荐同一标签下相关文章的功能，
试用了 hexo=recommend-posts,总是出现各种错误，
找到了一段js代码
https://ethanblog.com/tech/hexo-related-posts.html
但是需要在主题中加入这句代码：<%- related_posts(post, site.posts) %>
对jade不熟悉，不知道怎么把这段js代码利用起来，请大神指教，谢谢

**Comment by chaooo** [comment]
不兼容啊，找找hexo相关插件吧

**Comment by chdlong** [comment]
确实不兼容，我试了好几天了，呵呵
插件试过hexo-recommend-posts文章数一多就不能用了，有好多问题。
插件hexo-related-popular-posts，要想使用也需要在主题中添加内容，就和这段js代码要添加的一样，无语。
其它的插件找不到了，所以还是希望大神能把这个功能给加上，很期待呢！

**Comment by chdlong** [comment]
为了加上这个功能我临时抱佛脚，自学jade，嘻嘻
在post.jade文件中
-each wenz in site.posts
          -var sss=wenz.title;
感觉这两句没有问题，但是wenz的属性title,path,tags什么的都不能取，总提示
Cannot read property 'title' of undefined
site.posts中的对象数是对的，我已验证
实在找不出原因了，还请大神解惑，谢谢！

**Comment by chaooo** [comment]
目前比较忙，没时间去弄哦，对了，是不是应该遍历page.posts，而不是site.posts？

**Comment by chdlong** [comment]
您说的对！我再试，应该也很快就好了！
好的，你忙吧！感谢回复！！
