### ISSUE TITLE
界面优化建议

### ISSUE THREAD

**Issue by mingfuyan** [chaooo/hexo-theme-BlueLake#80]
原：
 标签
acm 小技巧 C++ 流控制函数 stl-map 种类并查集 题解 kuangbin带你飞 矩形相交

我想要：
 标签
acm 小技巧 
C++ 流控制函数 
stl-map 
种类并查集 
题解 
kuangbin带你飞 
矩形相交

**Comment by chaooo** [comment]
这样的话，标签太多容易把侧边栏撑的很长，建议自己写点样式覆盖默认样式
