### ISSUE TITLE
如果想把 sidebar 放左面，應該改那裡?

### ISSUE THREAD

**Issue by KenYKHo** [chaooo/hexo-theme-BlueLake#84]
請指教，謝謝。

**Comment by KenYKHo** [comment]
在 base.jade 對調 layout-g 內容： 

     #layout.layout-g
        if theme.widgets_on_small_screens
          .layout-r: #sidebar
            if theme.local_search == true
              .search-pla
              block tocmodel
            each item in theme.widgets
              != partial('_widget/' + item + '.jade')
        else
          .layout-r.hidden_mid_and_down: #sidebar
            each item in theme.widgets
              != partial('_widget/' + item + '.jade')
        .layout-l: .content_container
          block content

在 style.styl right更改為 left：

.content_container
  padding-left: 40px

#search-form 
  position: absolute
  bottom: -52px
  left:0

看看效果如何!!

**Comment by chaooo** [comment]
是的👍👍👍
