### ISSUE TITLE
您好， 我用gitalk但是出现问题， 显示异常，请问大佬如何解决

### ISSUE THREAD

**Issue by mingfuyan** [chaooo/hexo-theme-BlueLake#87]
[我的博客](https://solodance.top/about/)

请下滑查看详情， 谢谢

**Comment by chaooo** [comment]
检查 theme.comment.gitalk.enable 是否配置为true，
检查https://unpkg.com/gitalk/dist/gitalk.css是否正确引入

**Comment by mingfuyan** [comment]
请问如何检查https://unpkg.com/gitalk/dist/gitalk.css是否正确引入, 如果未正确引入 应当如何正确引入

**Comment by 841809077** [comment]
> 检查 theme.comment.gitalk.enable 是否配置为true，
> 检查[https://unpkg.com/gitalk/dist/gitalk.css是否正确引入](https://unpkg.com/gitalk/dist/gitalk.css%E6%98%AF%E5%90%A6%E6%AD%A3%E7%A1%AE%E5%BC%95%E5%85%A5)

大佬，gitalk相关的参数不会填呀，谁有教程啊？repo、client_id、client_secret、admin

**Comment by 841809077** [comment]
我 gitalk 配置可以了，现在将我的配置经验分享一下。
我的博客地址是：https://841809077.github.io，gitalk 配置如下：
----------------------
gitalk:
enable: true
owner: 841809077
repo: 841809077.github.io
client_id: 7ff67---------07324aa
client_secret: f1312asdd4d73----------aeb23423424099d
admin: 841809077
language: zh-CN
pagerDirection: last
----------------------
关于client_id和client_secret的值，可参考：https://zonghongyan.github.io/2017/06/29/201706292034/，其实gitment和gitalk在github准备工作上差不多。
----------------------
hexo d -g上传到 github 之后，每篇文章下面都出现了：
---
未找到相关的 Issues 进行评论
请联系 @841809077 初始化创建
使用 GitHub 登录
---
然后，我点击了按钮，出来了认证界面，点击完之后，gitalk评论框就出现了，对应的repo的issues里面也就有了记录。个人猜测，配置好gitalk之后，还需要将博客中的每个链接都点一遍，初始化一下issues记录，只不过这样有些麻烦，有没有简便方法呢？
