### ISSUE TITLE
移动端侧边栏显示优化

### ISSUE THREAD

**Issue by juejian** [chaooo/hexo-theme-BlueLake#89]
移动端的文章分类、标签、最近文章都显示在文章内容的底端。这个有点不合理，请教如何优化？

![1](https://user-images.githubusercontent.com/12257223/62406286-f38bc700-b5db-11e9-8945-7d0b8cd2fe92.jpg)

**Comment by chaooo** [comment]
主题配置文件中可以配置widgets_on_small_screens是否在小屏幕显示侧边栏，默认显示底部

**Comment by 841809077** [comment]
> 主题配置文件中可以配置widgets_on_small_screens是否在小屏幕显示侧边栏，默认显示底部

大佬，看来又更新了不少东西啊，我再来更新一下
