### ISSUE TITLE
前端。

### ISSUE THREAD

**Issue by WangShuai0413** [chaooo/hexo-theme-BlueLake#90]
作者你好。
很喜欢您写的这个web页面。
想用它自己去搭建一下后台。
请问您方不方便给我发一下这个web的html版的前端呢？

万分感谢。
Email: wshuai0413@163.com

**Comment by chaooo** [comment]
我的博客文件master分支是编译后的html文件[ https://github.com/chaooo/chaooo.github.io.git](https://github.com/chaooo/chaooo.github.io.git)
