### ISSUE TITLE
您好， 博客里的图片如何才能点击放大？

### ISSUE THREAD

**Issue by mingfuyan** [chaooo/hexo-theme-BlueLake#91]
您好， 博客里的图片如何才能点击放大？若是没有此功能望您有空时加一下~

**Comment by 841809077** [comment]
我看有的博客都用的插件 FancyBox，你研究出来了吗？

**Comment by 841809077** [comment]
https://841809077.github.io/，目前我的博客已经做出了图片放大的效果了，可以看一下，后续我会写篇教程。

**Comment by mingfuyan** [comment]
好的谢谢
