### ISSUE TITLE
语法高亮如何不要当前这种比较但的背景呢。

### ISSUE THREAD

**Issue by Gowa2017** [chaooo/hexo-theme-BlueLake#94]
如图，我想要这种效果怎么样自定义。

<img width="915" alt="image" src="https://user-images.githubusercontent.com/33367355/67934764-77694580-fc03-11e9-9a5e-0fc7b8445162.png">

补充一下：这个是hexo 默认主体的高亮风格，相当喜欢。

**Comment by chaooo** [comment]
可以自定义或下载其他代码高亮，替换路径`themes/BlueLake/source/css/highlight-dark.styl`
